#!/usr/bin/env bash
# configuring subdomain www to point to load balance
if [ $# -eq 1 ]
then
	sub_domains='www lb-01 web-01 web-02'
else
	sub_domains="$2"
fi
for sub in $sub_domains
do
# dig retrieves the DNS records and awk extract info from 14th line with NR
	echo -n "The subdomain $sub"
	dig "$sub.$1" | awk 'NR == 14 {printf " is a %s record and points to %s\n", $4, $5}'
done
