#!/usr/bin/env bash
#script to transfer a file from client to server

#check if thr number of parameters is less than 3
if [ "$#" -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    #transfer file with scp
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"

    # check the success of scp by checking exit status using $?
    # if ["$?" -eq 0 ];
    # then
    #     echo "File transfered successfully."
    # else
    #     echo "failed to transfer file"
    # fi
fi
