#!/usr/bin/env bash
#script to transfer a file from client to server

#check if thr number of parameters is less than 3
if [ "$#" -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign values to variables from commandline
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

#transfer file with scp
scp -o StrictHostKeyChecking=n0 -i "$path_to_file" "$path_to_file" "$username@$ip:~/"

# check the success of scp by checking exit status using $?
# if ["$?" -eq 0 ];
# then
#     echo "File transfered successfully."
# else
#     echo "failed to transfer file"
# fi
