#!/usr/bin/env bash
# install nginx and setup
sudo apt-get update
sudo apt-get -y install nginx
# listening on port 80 via nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22
sudo ufw --force enable
sudo ufw status
systemctl status nginx
# create an index.html file with "HelloWorld!" content and prevent output in terminal
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
