#!/usr/bin/env bash
# configure Nginx server so /redirect_me is redirecting to other page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "/listen 80 default_sserver;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx start
