#!/usr/bin/env bash
# configure Nginx server so /redirect_me is redirecting to other page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" sudo tee /var/www/html/index.html > /dev/null
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/hummingjay permanent;/" /etc/nginx/sites-available/default
service nginx start
