#!/usr/bin/env bash
# shellcheck disable=SC2154

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Define the custom header configuration string
custom_header="add_header X-Served-By \$hostname;"

# Add the custom header configuration to Nginx sites-available/default file
sudo sed -i "s/http {/$custom_header\n\nhttp {/" /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart

