#!/usr/bin/env bash
# FIzzBuzz @multiples 3 & 5 FIzz multiples of 3 Buzz @5's

for (( i=1; i <= 100; i++))
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
done
