#!/usr/bin/env bash
# bash scrip print bad luck on i=4 and goodluck @i=8 rest Best school

i=0
while [ $i -le 9 ]
do
	if [ $i = 3 ]
	then
		echo "bad luck"
	elif [ $i = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1))
done
