#!/usr/bin/env bash
# script displaying time 12hrs and 59 min

hour=0
while [ $hour -le 12 ]
do
	echo "Hour: "$hour
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo $minutes
		minutes=$((minutes + 1))
	done
	hour=$((hour + 1))
done
